In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset_path = "../datasets/diginetica"
griffin_dataset_path = "../griffin_datasets/diginetica-downsample-pk"

In [3]:
ctr_train = pd.read_parquet(f"{dataset_path}/ctr/ctr-100k_train.pqt")
ctr_validation = pd.read_parquet(f"{dataset_path}/ctr/ctr-100k_validation.pqt")
ctr_test = pd.read_parquet(f"{dataset_path}/ctr/ctr-100k_test.pqt")
# Update the clicked column to be a boolean
ctr_train["clicked"] = ctr_train["clicked"].astype(bool)
ctr_validation["clicked"] = ctr_validation["clicked"].astype(bool)
ctr_test["clicked"] = ctr_test["clicked"].astype(bool)
ctr_train['click_id'] = ctr_train.index
ctr_validation['click_id'] = ctr_validation.index
ctr_test['click_id'] = ctr_test.index

In [4]:
# construct a click_querytest dataframe combines ctr_train, ctr_validation, ctr_test
click_querytest = pd.concat([ctr_train, ctr_validation, ctr_test])
click_querytest

          queryId  itemId               timestamp  clicked  click_id
80440533   861044  468709 2016-08-05 06:58:49.079    False  80440533
80440420   861044   36016 2016-08-05 06:58:49.079    False  80440420
80440419   861044   36015 2016-08-05 06:58:49.079    False  80440419
80440418   861044   36014 2016-08-05 06:58:49.079    False  80440418
80440417   861044   36012 2016-08-05 06:58:49.079    False  80440417
...           ...     ...                     ...      ...       ...
19192252   240200   78132 2016-10-26 18:50:30.578    False  19192252
19192253   240200   87938 2016-10-26 18:50:30.578    False  19192253
19192254   240200  122178 2016-10-26 18:50:30.578    False  19192254
19192248   240200   66576 2016-10-26 18:50:30.578    False  19192248
19192259   240200  148942 2016-10-26 18:50:30.578    False  19192259

[119862 rows x 5 columns]

In [5]:
# Downsample the QueryResult dataframe
query_results = pd.read_parquet(f"{dataset_path}/data/query_results.pqt")

In [6]:
# Downsample the QueryResult dataframe
query_results = query_results.sample(frac=0.1, random_state=42)

In [7]:
query_results

        queryId  itemId               timestamp
109572   101333    9231 2016-05-14 03:55:36.557
604415   698225   19652 2016-03-15 19:45:58.098
441658   527341   16587 2016-02-06 02:55:24.838
469871   289877  128990 2016-05-29 22:42:19.089
851896   821678  174478 2016-04-11 17:03:11.515
...         ...     ...                     ...
155066   821816   36333 2016-05-30 19:07:20.504
146067    79839   13497 2016-03-25 01:54:27.152
490488   552221  188130 2016-02-04 03:53:10.591
466939   709132   89753 2016-04-24 09:26:28.984
361413   202657   57748 2016-05-02 23:46:02.273

[9227128 rows x 3 columns]

In [8]:
# Add primary key for click table
click = pd.read_parquet(f"{dataset_path}/data/clicks.pqt")
click["click_id"] = np.arange(len(click))
click

         queryId  itemId               timestamp  click_id
0              1   24857 2016-05-09 20:27:02.181         0
1          46255   30792 2016-05-09 20:28:08.232         1
2          46689    8252 2016-05-09 16:58:35.268         2
3          46731   33969 2016-05-09 20:25:56.888         3
4          46748    7837 2016-05-09 17:02:21.813         4
...          ...     ...                     ...       ...
1127759   980493   42906 2016-04-14 19:45:16.918   1127759
1127760   980493   33312 2016-04-14 19:45:27.425   1127760
1127761   980493   33312 2016-04-14 19:35:35.050   1127761
1127762   980493    5227 2016-04-14 19:44:19.554   1127762
1127763   980503   13296 2016-02-16 03:58:32.055   1127763

[1127764 rows x 4 columns]

In [9]:
query_results["query_result_id"] = np.arange(len(query_results))
query_results

        queryId  itemId               timestamp  query_result_id
109572   101333    9231 2016-05-14 03:55:36.557                0
604415   698225   19652 2016-03-15 19:45:58.098                1
441658   527341   16587 2016-02-06 02:55:24.838                2
469871   289877  128990 2016-05-29 22:42:19.089                3
851896   821678  174478 2016-04-11 17:03:11.515                4
...         ...     ...                     ...              ...
155066   821816   36333 2016-05-30 19:07:20.504          9227123
146067    79839   13497 2016-03-25 01:54:27.152          9227124
490488   552221  188130 2016-02-04 03:53:10.591          9227125
466939   709132   89753 2016-04-24 09:26:28.984          9227126
361413   202657   57748 2016-05-02 23:46:02.273          9227127

[9227128 rows x 4 columns]

In [10]:
view = pd.read_parquet(f"{dataset_path}/data/item_views.pqt")
view["view_id"] = np.arange(len(view))
view

         sessionId    userId  itemId               timestamp  view_id
0                1       NaN   81766 2016-05-09 16:03:29.629        0
1                1       NaN   31331 2016-05-09 16:11:54.338        1
2                1       NaN   32118 2016-05-09 15:58:46.889        2
3                1       NaN    9654 2016-05-09 15:55:59.168        3
4                1       NaN   32627 2016-05-09 16:13:15.728        4
...            ...       ...     ...                     ...      ...
1235375     600684       NaN   42906 2016-04-14 19:45:18.875  1235375
1235376     600684       NaN   33312 2016-04-14 19:45:29.544  1235376
1235377     600684       NaN   33312 2016-04-14 19:35:38.643  1235377
1235378     600684       NaN    5227 2016-04-14 19:44:21.298  1235378
1235379     600687  249347.0   13296 2016-02-16 03:58:34.480  1235379

[1235380 rows x 5 columns]

In [11]:
purchase = pd.read_parquet(f"{dataset_path}/data/purchases.pqt")
purchase["purchase_id"] = np.arange(len(purchase))
purchase

,sessionId,userId,ordernumber,itemId,timestamp,purchase_id
0,150,18278.0,16421,25911,2016-05-06 05:42:32.820,0
1,151,NaN,16290,175874,2016-05-06 02:21:59.832,1
2,156,7.0,21173,35324,2016-06-16 16:19:09.736,2
3,179,NaN,16924,31233,2016-05-09 15:28:48.713,3
4,246,34.0,16936,34677,2016-05-09 04:42:46.525,4
...,...,...,...,...,...,...
18020,600131,NaN,5675,40804,2016-03-18 06:10:06.463,18020
18021,600250,NaN,19629,33777,2016-05-21 18:37:20.278,18021
18022,600432,NaN,13928,17176,2016-04-25 09:36:30.154,18022
18023,600432,NaN,13928,13662,2016-04-25 09:36:30.154,18023
18024,600661,NaN,18363,379345,2016-05-15 08:02:06.036,18024

In [12]:
product_name_token = pd.read_parquet(f"{dataset_path}/data/product_name_tokens.pqt")
product_name_token["product_name_token_id"] = np.arange(len(product_name_token))
product_name_token

        itemId   token  product_name_token_id
0            1    4875                      0
0            1     776                      1
0            1   56689                      2
0            1   18212                      3
0            1   18212                      4
...        ...     ...                    ...
184046  387467   17260                 941640
184046  387467  130714                 941641
184046  387467  130714                 941642
184046  387467    3344                 941643
184046  387467  109312                 941644

[941645 rows x 3 columns]

In [13]:
query_searchstring_token = pd.read_parquet(f"{dataset_path}/data/query_searchstring_tokens.pqt")
query_searchstring_token["query_searchstring_token_id"] = np.arange(len(query_searchstring_token))
query_searchstring_token

       queryId   token  query_searchstring_token_id
0            1   16655                            0
0            1  244087                            1
0            1   51531                            2
0            1  529597                            3
0            1   58153                            4
...        ...     ...                          ...
81606    53450  296114                       138255
81607    53452  528937                       138256
81609    53453    5742                       138257
81609    53453  146356                       138258
81609    53453   41709                       138259

[138260 rows x 3 columns]

In [14]:
# Save the parquet files under griffin_dataset
import shutil
import os
shutil.rmtree(griffin_dataset_path, ignore_errors=True)
shutil.copytree(dataset_path, griffin_dataset_path)

'../griffin_datasets/diginetica-downsample-pk'

In [15]:
# remove the ctr folder
shutil.rmtree(f"{griffin_dataset_path}/ctr", ignore_errors=False)
os.mkdir(f"{griffin_dataset_path}/ctr")
# remove the query_results file
# if is a directory, remove it; if is a file, remove it
if os.path.isdir(f"{griffin_dataset_path}/data/query_results.pqt"):
    shutil.rmtree(f"{griffin_dataset_path}/data/query_results.pqt", ignore_errors=False)
else:
    os.remove(f"{griffin_dataset_path}/data/query_results.pqt")
# Save the parquet files under griffin dataset
query_results.to_parquet(f"{griffin_dataset_path}/data/query_results.pqt")
# Save to the griffin dataset
ctr_train.to_parquet(f"{griffin_dataset_path}/ctr/ctr-100k_train.pqt")
ctr_validation.to_parquet(f"{griffin_dataset_path}/ctr/ctr-100k_validation.pqt")
ctr_test.to_parquet(f"{griffin_dataset_path}/ctr/ctr-100k_test.pqt")

click_querytest.to_parquet(f"{griffin_dataset_path}/data/click_querytest.pqt")

click.to_parquet(f"{griffin_dataset_path}/data/clicks.pqt")
view.to_parquet(f"{griffin_dataset_path}/data/item_views.pqt")
purchase.to_parquet(f"{griffin_dataset_path}/data/purchases.pqt")
product_name_token.to_parquet(f"{griffin_dataset_path}/data/product_name_tokens.pqt")
query_searchstring_token.to_parquet(f"{griffin_dataset_path}/data/query_searchstring_tokens.pqt")

dataset_name: diginetica-downsample
tables:
  - name: Product
    source: data/products.pqt
    format: parquet
    columns:
      - name: itemId
        dtype: primary_key
      - name: categoryId
        dtype: category
      - name: pricelog2
        dtype: float
  - name: Click
    source: data/clicks.pqt
    format: parquet
    columns:
      - name: queryId
        dtype: foreign_key
        link_to: Query.queryId
      - name: itemId
        dtype: foreign_key
        link_to: Product.itemId
      - name: timestamp
        dtype: datetime
    time_column: timestamp
  - name: ClickQueryTest
    source: data/click_querytest.pqt
    format: parquet
    columns:
      - name: click_id
        dtype: primary_key
      - name: queryId
        dtype: foreign_key
        link_to: Query.queryId
      - name: itemId
        dtype: foreign_key
        link_to: Product.itemId
      - name: clicked
        dtype: category
      - name: timestamp
        dtype: datetime
    time_column: timestamp
  - name: QueryResult
    source: data/query_results.pqt
    format: parquet
    columns:
      - name: query_result_id
        dtype: primary_key
      - name: queryId
        dtype: foreign_key
        link_to: Query.queryId
      - name: itemId
        dtype: foreign_key
        link_to: Product.itemId
      - name: timestamp
        dtype: datetime
    time_column: timestamp
  - name: View
    source: data/item_views.pqt
    format: parquet
    columns:
      - name: view_id
        dtype: primary_key
      - name: sessionId
        dtype: foreign_key
        link_to: Session.id
      - name: userId
        dtype: foreign_key
        link_to: User.id
      - name: itemId
        dtype: foreign_key
        link_to: Product.itemId
      - name: timestamp
        dtype: datetime
    time_column: timestamp
  - name: Purchase
    source: data/purchases.pqt
    format: parquet
    columns:
      - name: purchase_id
        dtype: primary_key
      - name: sessionId
        dtype: foreign_key
        link_to: Session.id
      - name: userId
        dtype: foreign_key
        link_to: User.id
      - name: itemId
        dtype: foreign_key
        link_to: Product.itemId
      - name: ordernumber
        dtype: foreign_key
        link_to: Orders.id
      - name: timestamp
        dtype: datetime
    time_column: timestamp
  - name: Query
    source: data/queries.pqt
    format: parquet
    columns:
      - name: queryId
        dtype: primary_key
      - name: sessionId
        dtype: foreign_key
        link_to: Session.id
      - name: userId
        dtype: foreign_key
        link_to: User.id
      - name: duration
        dtype: float
      - name: categoryId
        dtype: category
      - name: timestamp
        dtype: datetime
    time_column: timestamp
  - name: ProductNameToken
    source: data/product_name_tokens.pqt
    format: parquet
    columns:
      - name: product_name_token_id
        dtype: primary_key
      - name: itemId
        dtype: foreign_key
        link_to: Product.itemId
      - name: token
        dtype: foreign_key
        link_to: Token.id
  - name: QuerySearchstringToken
    source: data/query_searchstring_tokens.pqt
    format: parquet
    columns:
      - name: query_searchstring_token_id
        dtype: primary_key
      - name: queryId
        dtype: foreign_key
        link_to: Query.queryId
      - name: token
        dtype: foreign_key
        link_to: Token.id
tasks:
  - name: ctr
    source: ctr/ctr-100k_{split}.pqt
    format: parquet
    columns:
      - name: click_id
        dtype: primary_key
      - name: itemId
        dtype: foreign_key
        link_to: Product.itemId
      - name: queryId
        dtype: foreign_key
        link_to: Query.queryId
      - name: timestamp
        dtype: datetime
      - name: clicked
        dtype: category
    time_column: timestamp
    evaluation_metric: auroc
    target_column: clicked
    target_table: ClickQueryTest
    task_type: classification
  - name: purchase
    source: purchase/purchase_{split}.pqt
    format: parquet
    columns:
      - name: itemId
        dtype: foreign_key
        link_to: Product.itemId
      - name: sessionId
        dtype: foreign_key
        link_to: Session.id
      - name: timestamp
        dtype: datetime
    time_column: timestamp
    evaluation_metric: mrr
    target_column: itemId
    target_table: Purchase
    task_type: retrieval