In [1]:
import numpy as np
import pandas as pd
import os
import shutil
import yaml

In [2]:
dataset_path = "../datasets/amazon"
griffin_path = "../griffin_datasets/amazon"

In [3]:
# Add primary key to review
review = pd.read_parquet(os.path.join(dataset_path, "data/review.pqt"))
review

,review_time,customer_id,product_id,rating,verified,review_text,summary
__null_dask_index__,,,,,,,
0,2005-03-30,0,14,5.0,False,"The King, the Mice and the Cheese by Nancy Gur...",A story children will love and learn from
3,2015-07-09,3,14,5.0,False,LOVE IT,Five Stars
4,2015-01-18,4,14,5.0,True,Great!,Five Stars
5,2013-11-03,5,14,5.0,False,Over and over the king has problems. Fortunat...,Not Nice Mice
6,2013-10-08,6,14,5.0,True,I remember reading my parents' copy of this bo...,One of my favorite kids' stories
...,...,...,...,...,...,...,...
21935275,2014-08-16,188216,506009,5.0,False,This was a wonderful Christmas story. I think ...,Great Christmas Read. Up there with The Night ...
21935276,2014-08-13,1260982,506009,4.0,False,The Age of Not Believing provides a positive m...,A Positive Message for Children
21935279,2012-12-02,319196,506010,5.0,False,"This past year fans of ""Charlie's Angels"" were...","""NOW THIS IS THE COMPANION TO THE ""CHARLIE'S A..."
21935280,2008-12-15,1407251,506010,5.0,True,"For any fan of Charlie's Angels, this book is ...",An Excellent Case!
21935281,2007-06-15,1373107,506010,3.0,False,To review this book I will divide it into two ...,Great Stories But A Little One-Sided

In [8]:
review["review_id"] = review.index
review

,review_time,customer_id,product_id,rating,verified,review_text,summary,review_id
__null_dask_index__,,,,,,,,
0,2005-03-30,0,14,5.0,False,"The King, the Mice and the Cheese by Nancy Gur...",A story children will love and learn from,0
3,2015-07-09,3,14,5.0,False,LOVE IT,Five Stars,3
4,2015-01-18,4,14,5.0,True,Great!,Five Stars,4
5,2013-11-03,5,14,5.0,False,Over and over the king has problems. Fortunat...,Not Nice Mice,5
6,2013-10-08,6,14,5.0,True,I remember reading my parents' copy of this bo...,One of my favorite kids' stories,6
...,...,...,...,...,...,...,...,...
21935275,2014-08-16,188216,506009,5.0,False,This was a wonderful Christmas story. I think ...,Great Christmas Read. Up there with The Night ...,21935275
21935276,2014-08-13,1260982,506009,4.0,False,The Age of Not Believing provides a positive m...,A Positive Message for Children,21935276
21935279,2012-12-02,319196,506010,5.0,False,"This past year fans of ""Charlie's Angels"" were...","""NOW THIS IS THE COMPANION TO THE ""CHARLIE'S A...",21935279
21935280,2008-12-15,1407251,506010,5.0,True,"For any fan of Charlie's Angels, this book is ...",An Excellent Case!,21935280
21935281,2007-06-15,1373107,506010,3.0,False,To review this book I will divide it into two ...,Great Stories But A Little One-Sided,21935281

In [4]:
rating_train = pd.read_parquet(os.path.join(dataset_path, "rating/train.pqt"))
rating_validation = pd.read_parquet(os.path.join(dataset_path, "rating/validation.pqt"))
rating_test = pd.read_parquet(os.path.join(dataset_path, "rating/test.pqt"))

In [13]:
# find a row in review with review_id of 2877192
review[review["review_id"] == 2877192]

,review_time,customer_id,product_id,rating,verified,review_text,summary,review_id
__null_dask_index__,,,,,,,,
2877192,2015-12-31,1026946,41419,5.0,True,Love this,Five Stars,2877192

In [5]:
rating_train

         review_time  customer_id  product_id  rating
6286835   2015-12-17       133303      107128     2.0
16861804  2015-12-17      1654571      459966     5.0
20746152  2015-12-17      1475897      326226     5.0
10594214  2015-12-17       823335      266184     5.0
20745975  2015-12-17      1489058      326209     5.0
...              ...          ...         ...     ...
15825985  2015-12-29       695949      405590     1.0
1727902   2015-12-29       773364       24357     5.0
9794245   2015-12-29       311801      243483     5.0
14671638  2015-12-29       929060      353805     4.0
9797018   2015-12-29       169009      243512     5.0

[78485 rows x 4 columns]

In [12]:
rating_test

         review_time  customer_id  product_id  rating
2877192   2015-12-31      1026946       41419     5.0
10535928  2015-12-31      1101570      264606     5.0
14746938  2015-12-31      1504230      356690     5.0
13562605  2015-12-31       504294      332099     5.0
20352691  2015-12-31       397266      259237     4.0
...              ...          ...         ...     ...
8570767   2016-01-01      1601009      181751     4.0
2117284   2016-01-01       267500       28481     5.0
2117285   2016-01-01        98737       28481     3.0
4832867   2016-01-01       167613       76000     5.0
3264632   2016-01-01      1101669       49683     4.0

[13492 rows x 4 columns]

In [12]:
rating_train["review_id"] = rating_train.index
rating_validation["review_id"] = rating_validation.index
rating_test["review_id"] = rating_test.index

In [14]:
# save to parquet
# copy the whold dataset to griffin_datasets
shutil.rmtree(griffin_path, ignore_errors=True)
shutil.copytree(dataset_path, griffin_path)

# save to parquet
shutil.rmtree(os.path.join(griffin_path, "data", "review.pqt"), ignore_errors=False)
shutil.rmtree(os.path.join(griffin_path, "rating"), ignore_errors=False)
os.makedirs(os.path.join(griffin_path, "rating"), exist_ok=True)
review.to_parquet(os.path.join(griffin_path, "data/review.pqt"))
rating_train.to_parquet(os.path.join(griffin_path, "rating/train.pqt"))
rating_validation.to_parquet(os.path.join(griffin_path, "rating/validation.pqt"))
rating_test.to_parquet(os.path.join(griffin_path, "rating/test.pqt"))

dataset_name: Amazon
tables:
  - name: Customer
    source: data/customer.pqt
    format: parquet
    columns:
      - name: customer_id
        dtype: primary_key
  - name: Product
    source: data/product.pqt
    format: parquet
    columns:
      - name: brand
        dtype: text
      - name: category
        dtype: text
      - name: description
        dtype: text
      - name: price
        dtype: float
      - name: title
        dtype: text
      - name: product_id
        dtype: primary_key
  - name: Review
    source: data/review.pqt
    format: parquet
    columns:
      - name: review_id
        dtype: primary_key
      - name: rating
        dtype: float
      - name: review_text
        dtype: text
      - name: review_time
        dtype: datetime
      - name: summary
        dtype: text
      - name: verified
        dtype: category
      - name: customer_id
        dtype: foreign_key
        link_to: Customer.customer_id
      - name: product_id
        dtype: foreign_key
        link_to: Product.product_id
    time_column: review_time
tasks:
  - name: rating
    source: rating/{split}.pqt
    format: parquet
    columns:
      - name: review_id
        dtype: primary_key
      - name: review_time
        dtype: datetime
      - name: customer_id
        dtype: foreign_key
        link_to: Customer.customer_id
      - name: product_id
        dtype: foreign_key
        link_to: Product.product_id
      - name: rating
        dtype: float
    time_column: review_time
    evaluation_metric: rmse
    target_column: rating
    target_table: Review
    task_type: regression
  - name: purchase
    source: purchase/{split}.pqt
    format: parquet
    columns:
      - name: customer_id
        dtype: foreign_key
        link_to: Customer.customer_id
      - name: product_id
        dtype: foreign_key
        link_to: Product.product_id
      - name: prediction_timestamp
        dtype: datetime
    time_column: prediction_timestamp
    evaluation_metric: mrr
    target_column: product_id
    target_table: Review
    task_type: retrieval
  - name: churn
    source: churn/{split}.pqt
    format: parquet
    columns:
      - name: timestamp
        dtype: datetime
      - name: customer_id
        dtype: primary_key
      - name: churn
        dtype: category
    time_column: timestamp
    evaluation_metric: auroc
    target_column: churn
    target_table: Customer
    task_type: classification