In [1]:
import numpy as np
import pandas as pd
import os
import shutil

In [13]:
dataset_path = "../datasets/avs"
griffin_path = "../griffin_datasets/avs-pk"

In [3]:
history = pd.read_parquet(os.path.join(dataset_path, "data", "history.pqt"))

In [4]:
history

,id,chain,offer,market,repeattrips,repeater,offerdate
__null_dask_index__,,,,,,,
0,86246,205,1208251,34,5,t,2013-04-24
1,86252,205,1197502,34,16,t,2013-03-27
2,12682470,18,1197502,11,0,f,2013-03-28
3,12996040,15,1197502,9,0,f,2013-03-25
4,13089312,15,1204821,9,0,f,2013-04-01
...,...,...,...,...,...,...,...
160052,4712158291,214,1208329,8,0,f,2013-04-22
160053,4715039820,166,1208329,14,0,f,2013-04-24
160054,4797277036,152,1203052,10,6,t,2013-04-02
160055,4804019740,153,1204822,12,0,f,2013-04-17
160056,4809911000,153,1204822,12,0,f,2013-04-05

In [5]:
history['history_id'] = history.index

In [6]:
history

,id,chain,offer,market,repeattrips,repeater,offerdate,history_id
__null_dask_index__,,,,,,,,
0,86246,205,1208251,34,5,t,2013-04-24,0
1,86252,205,1197502,34,16,t,2013-03-27,1
2,12682470,18,1197502,11,0,f,2013-03-28,2
3,12996040,15,1197502,9,0,f,2013-03-25,3
4,13089312,15,1204821,9,0,f,2013-04-01,4
...,...,...,...,...,...,...,...,...
160052,4712158291,214,1208329,8,0,f,2013-04-22,160052
160053,4715039820,166,1208329,14,0,f,2013-04-24,160053
160054,4797277036,152,1203052,10,6,t,2013-04-02,160054
160055,4804019740,153,1204822,12,0,f,2013-04-17,160055
160056,4809911000,153,1204822,12,0,f,2013-04-05,160056

In [7]:
repeater_train = pd.read_parquet(os.path.join(dataset_path, "repeater", "train.pqt"))
repeater_validation = pd.read_parquet(os.path.join(dataset_path, "repeater", "validation.pqt"))
repeater_test = pd.read_parquet(os.path.join(dataset_path, "repeater", "test.pqt"))

In [8]:
repeater_train

,id,chain,offer,market,repeater,offerdate,timestamp
__null_dask_index__,,,,,,,
19361,444360313,64,1194044,21,f,2013-03-01,2013-04-19
18130,438322272,64,1194044,21,t,2013-03-01,2013-04-19
18126,438260599,64,1194044,21,f,2013-03-01,2013-04-19
22234,455345546,64,1194044,21,t,2013-03-01,2013-04-19
18113,438159577,64,1194044,21,t,2013-03-01,2013-04-19
...,...,...,...,...,...,...,...
149647,4627716275,153,1204821,12,f,2013-04-19,2013-04-19
116095,2945325622,20,1204821,7,f,2013-04-19,2013-04-19
158056,4639773207,152,1203052,10,f,2013-04-19,2013-04-19
139607,4280568324,510,1200582,96,t,2013-04-19,2013-04-19
20665,450238984,165,1197502,21,f,2013-04-19,2013-04-19

In [9]:
repeater_train['history_id'] = repeater_train.index
repeater_validation['history_id'] = repeater_validation.index
repeater_test['history_id'] = repeater_test.index

In [10]:
repeater_test

,id,chain,offer,market,repeater,offerdate,timestamp,history_id
__null_dask_index__,,,,,,,,
36365,497284101,21,1208501,10,t,2013-04-25,2013-04-30,36365
89337,1877868358,98,1204576,8,f,2013-04-25,2013-04-30,89337
35066,496886907,21,1208329,10,f,2013-04-25,2013-04-30,35066
144767,4620551431,6,1208329,4,f,2013-04-25,2013-04-30,144767
121930,3378406714,431,1208251,35,t,2013-04-25,2013-04-30,121930
...,...,...,...,...,...,...,...,...
36040,497179623,21,1208501,10,f,2013-04-30,2013-04-30,36040
100805,2431870212,46,1208252,15,f,2013-04-30,2013-04-30,100805
90582,1915938005,240,1208501,12,t,2013-04-30,2013-04-30,90582
132645,3805419468,96,1208251,27,t,2013-04-30,2013-04-30,132645
11288,308855778,360,1208501,37,f,2013-04-30,2013-04-30,11288

In [11]:
# downsample the transactions table
transactions = pd.read_parquet(os.path.join(dataset_path, "data", "transactions.pqt"))
transactions = transactions.sample(frac=0.1, random_state=42)
transactions

,id,chain,dept,category,company,brand,date,productsize,productmeasure,purchasequantity,purchaseamount
__null_dask_index__,,,,,,,,,,,
757322,751326413,126,0,0,10000,0,2012-12-17,0.00,None,1,0.00
194658,3678640632,46,99,9909,107143070,5072,2012-03-11,12.00,OZ,2,2.67
524455,613922234,140,29,2930,103760030,8501,2012-11-09,7.50,OZ,2,4.58
499128,496316064,21,73,7308,103660232,15274,2013-03-14,24.00,CT,1,1.79
481223,744722619,58,41,4105,101111010,9907,2012-12-20,28.00,OZ,1,1.29
...,...,...,...,...,...,...,...,...,...,...,...
673562,258850159,2,16,1604,102200020,13228,2012-12-17,14.00,CT,1,1.00
354363,476149961,70,41,4107,1072543979,40679,2012-04-28,15.25,OZ,2,0.81
701043,4056166254,524,75,7507,1031074232,13390,2012-08-12,4.00,OZ,1,5.49
688404,1776027321,191,27,2710,103320030,875,2012-10-28,20.00,LB,1,7.99
409690,1990553114,507,36,3630,104900040,23359,2012-10-08,144.00,OZ,3,10.50

In [12]:
# Add a primary key to the transactions table
transactions['transaction_id'] = np.arange(len(transactions))
transactions

,id,chain,dept,category,company,brand,date,productsize,productmeasure,purchasequantity,purchaseamount,transaction_id
__null_dask_index__,,,,,,,,,,,,
757322,751326413,126,0,0,10000,0,2012-12-17,0.00,None,1,0.00,0
194658,3678640632,46,99,9909,107143070,5072,2012-03-11,12.00,OZ,2,2.67,1
524455,613922234,140,29,2930,103760030,8501,2012-11-09,7.50,OZ,2,4.58,2
499128,496316064,21,73,7308,103660232,15274,2013-03-14,24.00,CT,1,1.79,3
481223,744722619,58,41,4105,101111010,9907,2012-12-20,28.00,OZ,1,1.29,4
...,...,...,...,...,...,...,...,...,...,...,...,...
673562,258850159,2,16,1604,102200020,13228,2012-12-17,14.00,CT,1,1.00,34965574
354363,476149961,70,41,4107,1072543979,40679,2012-04-28,15.25,OZ,2,0.81,34965575
701043,4056166254,524,75,7507,1031074232,13390,2012-08-12,4.00,OZ,1,5.49,34965576
688404,1776027321,191,27,2710,103320030,875,2012-10-28,20.00,LB,1,7.99,34965577
409690,1990553114,507,36,3630,104900040,23359,2012-10-08,144.00,OZ,3,10.50,34965578

In [14]:
# copy the data to the griffin dataset
shutil.rmtree(griffin_path, ignore_errors=True)
shutil.copytree(dataset_path, griffin_path)

# remove the history table
shutil.rmtree(os.path.join(griffin_path, "data", "history.pqt"), ignore_errors=False)
history.to_parquet(os.path.join(griffin_path, "data", "history.pqt"))

# remove the transactions table
shutil.rmtree(os.path.join(griffin_path, "data", "transactions.pqt"), ignore_errors=False)
transactions.to_parquet(os.path.join(griffin_path, "data", "transactions.pqt"))

shutil.rmtree(os.path.join(griffin_path, "repeater"), ignore_errors=False)
os.mkdir(os.path.join(griffin_path, "repeater"))

repeater_train.to_parquet(os.path.join(griffin_path, "repeater", "train.pqt"))
repeater_validation.to_parquet(os.path.join(griffin_path, "repeater", "validation.pqt"))
repeater_test.to_parquet(os.path.join(griffin_path, "repeater", "test.pqt"))

dataset_name: avs
tables:
  - name: History
    source: data/history.pqt
    format: parquet
    columns:
      - name: history_id
        dtype: primary_key
      - name: chain
        dtype: foreign_key
        link_to: Chain.id
      - name: market
        dtype: category
      - name: offerdate
        dtype: datetime
      - name: id
        dtype: foreign_key
        link_to: Customer.id
      - name: offer
        dtype: foreign_key
        link_to: Offer.offer
    time_column: offerdate
  - name: Offer
    source: data/offers.pqt
    format: parquet
    columns:
      - name: brand
        dtype: foreign_key
        link_to: Brand.id
      - name: category
        dtype: foreign_key
        link_to: Category.id
      - name: company
        dtype: foreign_key
        link_to: Company.id
      - name: offervalue
        dtype: float
      - name: quantity
        dtype: float
      - name: offer
        dtype: primary_key
    time_column: null
  - name: Transaction
    source: data/transactions.pqt
    format: parquet
    columns:
      - name: transaction_id
        dtype: primary_key
      - name: brand
        dtype: foreign_key
        link_to: Brand.id
      - name: category
        dtype: foreign_key
        link_to: Category.id
      - name: chain
        dtype: foreign_key
        link_to: Chain.id
      - name: company
        dtype: foreign_key
        link_to: Company.id
      - name: date
        dtype: datetime
      - name: dept
        dtype: category
      - name: productmeasure
        dtype: category
      - name: productsize
        dtype: float
      - name: purchaseamount
        dtype: float
      - name: purchasequantity
        dtype: float
      - name: id
        dtype: foreign_key
        link_to: Customer.id
    time_column: date
tasks:
  - name: repeater
    source: repeater/{split}.pqt
    format: parquet
    columns:
      - name: history_id
        dtype: primary_key
      - name: market
        dtype: category
      - name: offerdate
        dtype: datetime
      - name: id
        dtype: foreign_key
        link_to: Customer.id
      - name: offer
        dtype: foreign_key
        link_to: Offer.offer
      - name: timestamp
        dtype: datetime
      - name: repeater
        dtype: category
    time_column: timestamp
    evaluation_metric: auroc
    target_column: repeater
    target_table: History
    task_type: classification