In [1]:
import pandas as pd
import numpy as np

dataset_path = "../griffin_datasets/rel-avito"
griffin_path = "../griffin_datasets/rel-avito-pk"

In [2]:

location = pd.read_parquet(f"{dataset_path}/Location.pqt")
# turn region_id and city_id to category, by
# 1. step 1: turning the nan to None
# 2. step 2: turning the left float to int
for col in ["RegionID", "CityID"]:
    location[col] = location[col].astype("Int64")
location

      LocationID  Level  RegionID  CityID
0              0    2.0        70    3024
1              1    3.0        56    2791
2              2    3.0        56    1139
3              3    3.0        64    3660
4              4    3.0        63    1324
...          ...    ...       ...     ...
3507        3507    3.0        14    3414
3508        3508    3.0        49    2821
3509        3509    3.0        14     359
3510        3510    3.0        36    2834
3511        3511    3.0        13     278

[3512 rows x 4 columns]

In [3]:
SearchInfo = pd.read_parquet(f"{dataset_path}/SearchInfo.pqt")
SearchInfo["IPID"] = SearchInfo["IPID"].astype("Int64")
SearchInfo

,UserID,SearchID,SearchDate,IPID,IsUserLoggedOn,SearchQuery,LocationID,CategoryID
0,2139,0,2015-04-25 00:00:01,837134,1.0,None,497,34
1,1477,1,2015-04-25 00:00:02,2187370,0.0,None,334,22
2,68959,2,2015-04-25 00:00:02,2089629,1.0,None,497,60
3,58818,3,2015-04-25 00:00:03,63549,1.0,sony playstation 4,375,0
4,30136,4,2015-04-25 00:00:04,1727717,0.0,None,334,38
...,...,...,...,...,...,...,...,...
1987151,87797,1987151,2015-05-13 23:59:51,1065752,1.0,None,334,60
1987152,66281,1987152,2015-05-13 23:59:51,2209435,0.0,imac,497,17
1987153,97377,1987153,2015-05-13 23:59:55,1848828,0.0,None,190,34
1987154,78797,1987154,2015-05-13 23:59:58,684886,1.0,None,1,26
1987155,10502,1987155,2015-05-13 23:59:59,2103041,0.0,None,497,35

In [4]:
SearchStream = pd.read_parquet(f"{dataset_path}/SearchStream.pqt")
SearchStream["SearchStreamID"] = np.arange(len(SearchStream))
for col in ["Position", "ObjectType", "IsClick"]:
    SearchStream[col] = SearchStream[col].astype("Int64")
SearchStream

,SearchID,AdID,Position,ObjectType,HistCTR,IsClick,SearchDate,SearchStreamID
0,541363,806173,8,1,NaN,<NA>,2015-04-30 20:57:06,0
1,541363,4316980,2,1,NaN,<NA>,2015-04-30 20:57:06,1
2,541363,2059012,7,1,NaN,<NA>,2015-04-30 20:57:06,2
3,541363,1586570,6,1,NaN,<NA>,2015-04-30 20:57:06,3
4,541363,5827116,1,3,0.005902,0,2015-04-30 20:57:06,4
...,...,...,...,...,...,...,...,...
9254697,272219,2115003,7,3,0.004097,0,2015-04-28 05:56:10,7107272
9254698,801957,2115003,7,3,0.004419,0,2015-05-03 21:02:17,7107273
9254699,801957,4769362,1,3,0.012318,0,2015-05-03 21:02:17,7107274
9254700,1034975,1738506,2,1,NaN,<NA>,2015-05-05 21:41:22,7107275
9254701,1034975,976832,1,3,0.000010,0,2015-05-05 21:41:22,7107276

In [5]:
PhoneRequestsStream = pd.read_parquet(f"{dataset_path}/PhoneRequestsStream.pqt")
PhoneRequestsStream["PhoneRequestID"] = np.arange(len(PhoneRequestsStream))
PhoneRequestsStream["IPID"] = PhoneRequestsStream["IPID"].astype("Int64")
PhoneRequestsStream

        UserID     IPID     AdID    PhoneRequestDate  PhoneRequestID
0        38950  1629303  1938326 2015-04-25 11:50:35               0
1        38950  1629303  3917327 2015-04-25 11:51:14               1
2        18761   109220  3806832 2015-04-25 12:07:43               2
3        18761   109220   573126 2015-04-25 12:20:11               3
4        38950  1629303  1938326 2015-04-25 12:39:22               4
...        ...      ...      ...                 ...             ...
302740    <NA>  1850902  1503766 2015-05-13 22:16:59          244430
302741    <NA>  1920287     <NA> 2015-05-13 22:45:32          244431
302742    <NA>  1153190     <NA> 2015-05-13 22:47:11          244432
302743    <NA>  2254444     <NA> 2015-05-13 23:12:37          244433
302744    <NA>  1009284   552514 2015-05-13 23:37:46          244434

[244435 rows x 5 columns]

In [6]:
UserInfo = pd.read_parquet(f"{dataset_path}/UserInfo.pqt")
for col in ["UserID", "UserAgentID", "UserAgentOSID", "UserAgentFamilyID", "UserDeviceID"]:
    UserInfo[col] = UserInfo[col].astype("Int64")
    # Add turn nan to MaxID + 1
    UserInfo[col] = UserInfo[col].fillna(UserInfo[col].max() + 1)
UserInfo

       UserID  UserAgentID  UserAgentOSID  UserDeviceID  UserAgentFamilyID
0           0        54898             20          2014                 85
1           1        15248             35          4093                 25
2           2        12555             30          2019                  9
3           3        18624              7          2014                 64
4           4        44754             51          3296                 18
...       ...          ...            ...           ...                ...
98245   98245        27407             35           135                 63
98246   98246        52045             35           871                 62
98247   98247         1027             20          2014                  7
98248   98248        63091             20          2014                 25
98249   98249        35241             43          2014                 62

[98250 rows x 5 columns]

In [7]:
VisitStream = pd.read_parquet(f"{dataset_path}/VisitStream.pqt")
VisitStream["VisitID"] = np.arange(len(VisitStream))
VisitStream["IPID"] = VisitStream["IPID"].astype("Int64")
VisitStream

         UserID     IPID     AdID            ViewDate  VisitID
1092      20812   965680  2007763 2015-04-25 04:07:16        0
1093       9281    76075    62087 2015-04-25 08:07:31        1
1094       9281    76075  4459210 2015-04-25 08:08:38        2
1095       9281    76075  3366402 2015-04-25 08:12:30        3
1096       9281    76075  5742539 2015-04-25 08:13:01        4
...         ...      ...      ...                 ...      ...
6449505    <NA>   118228  3333694 2015-05-13 23:52:32  5277856
6449506    <NA>   626754     <NA> 2015-05-13 23:54:42  5277857
6449507    <NA>  1387203     <NA> 2015-05-13 23:55:24  5277858
6449508    <NA>  1797231  4012649 2015-05-13 23:57:59  5277859
6449509    <NA>   694972     <NA> 2015-05-13 23:59:18  5277860

[5277861 rows x 5 columns]

In [8]:
user_visits_train = pd.read_parquet(f"{dataset_path}/user-visits/train.pqt")
user_visits_test = pd.read_parquet(f"{dataset_path}/user-visits/test.pqt")
user_visits_validation = pd.read_parquet(f"{dataset_path}/user-visits/validation.pqt")

In [9]:
# change the column num_click to num_visits
user_visits_train.rename(columns={"num_click": "num_visits"}, inplace=True)
user_visits_test.rename(columns={"num_click": "num_visits"}, inplace=True)
user_visits_validation.rename(columns={"num_click": "num_visits"}, inplace=True)

user_visits_train

       UserID  timestamp  num_visits
0       38950 2015-04-26        True
1       35404 2015-04-26        True
2       85455 2015-04-26        True
3        2871 2015-04-26        True
4       34600 2015-04-26        True
...       ...        ...         ...
86614   88581 2015-05-04       False
86615   46957 2015-04-26       False
86616    5298 2015-05-04       False
86617   22496 2015-05-04       False
86618   44054 2015-04-26       False

[86619 rows x 3 columns]

In [10]:
# Save the parquet files under griffin_dataset
import shutil
import os
shutil.rmtree(griffin_path, ignore_errors=True)
shutil.copytree(dataset_path, griffin_path)

'../griffin_datasets/rel-avito-pk'

In [11]:
SearchStream.to_parquet(f"{griffin_path}/SearchStream.pqt")
PhoneRequestsStream.to_parquet(f"{griffin_path}/PhoneRequestsStream.pqt")
VisitStream.to_parquet(f"{griffin_path}/VisitStream.pqt")
UserInfo.to_parquet(f"{griffin_path}/UserInfo.pqt")
location.to_parquet(f"{griffin_path}/Location.pqt")
SearchInfo.to_parquet(f"{griffin_path}/SearchInfo.pqt")

user_visits_train.to_parquet(f"{griffin_path}/user-visits/train.pqt")
user_visits_test.to_parquet(f"{griffin_path}/user-visits/test.pqt")
user_visits_validation.to_parquet(f"{griffin_path}/user-visits/validation.pqt")

column_groups: null
dataset_name: rel-avito
tables:
- columns:
  - dtype: primary_key
    name: LocationID
  - dtype: float
    name: Level
  - dtype: category
    name: RegionID
  - dtype: category
    name: CityID
  format: parquet
  name: Location
  source: Location.pqt
  time_column: null
- columns:
  - dtype: foreign_key
    link_to: UserInfo.UserID
    name: UserID
  - dtype: primary_key
    name: SearchID
  - dtype: datetime
    name: SearchDate
  - dtype: foreign_key
    link_to: IPInfo.IPID
    name: IPID
  - dtype: float
    name: IsUserLoggedOn
  - dtype: category
    name: SearchQuery
  - dtype: foreign_key
    link_to: Location.LocationID
    name: LocationID
  - dtype: foreign_key
    link_to: Category.CategoryID
    name: CategoryID
  format: parquet
  name: SearchInfo
  source: SearchInfo.pqt
  time_column: SearchDate
- columns:
  - dtype: primary_key
    name: SearchStreamID
  - dtype: foreign_key
    link_to: SearchInfo.SearchID
    name: SearchID
  - dtype: foreign_key
    link_to: AdsInfo.AdID
    name: AdID
  - dtype: category
    name: Position
  - dtype: category
    name: ObjectType
  - dtype: float
    name: HistCTR
  - dtype: category
    name: IsClick
  - dtype: datetime
    name: SearchDate
  format: parquet
  name: SearchStream
  source: SearchStream.pqt
  time_column: SearchDate
- columns:
  - dtype: primary_key
    name: PhoneRequestID
  - dtype: foreign_key
    link_to: UserInfo.UserID
    name: UserID
  - dtype: foreign_key
    link_to: IPInfo.IPID
    name: IPID
  - dtype: foreign_key
    link_to: AdsInfo.AdID
    name: AdID
  - dtype: datetime
    name: PhoneRequestDate
  format: parquet
  name: PhoneRequestsStream
  source: PhoneRequestsStream.pqt
  time_column: PhoneRequestDate
- columns:
  - dtype: primary_key
    name: UserID
  - dtype: foreign_key
    link_to: UserAgent.UserAgentID
    name: UserAgentID
  - dtype: foreign_key
    link_to: UserAgentOS.UserAgentOSID
    name: UserAgentOSID
  - dtype: foreign_key
    link_to: UserDevice.UserDeviceID
    name: UserDeviceID
  - dtype: foreign_key
    link_to: UserAgentFamily.UserAgentFamilyID
    name: UserAgentFamilyID
  format: parquet
  name: UserInfo
  source: UserInfo.pqt
  time_column: null
- columns:
  - dtype: primary_key
    name: CategoryID
  - dtype: category
    name: Level
  - dtype: category
    name: ParentCategoryID
  - dtype: category
    name: SubcategoryID
  format: parquet
  name: Category
  source: Category.pqt
  time_column: null
- columns:
  - dtype: primary_key
    name: VisitID
  - dtype: foreign_key
    link_to: UserInfo.UserID
    name: UserID
  - dtype: foreign_key
    link_to: IPInfo.IPID
    name: IPID
  - dtype: foreign_key
    link_to: AdsInfo.AdID
    name: AdID
  - dtype: datetime
    name: ViewDate
  format: parquet
  name: VisitStream
  source: VisitStream.pqt
  time_column: ViewDate
- columns:
  - dtype: primary_key
    name: AdID
  - dtype: foreign_key
    link_to: Location.LocationID
    name: LocationID
  - dtype: foreign_key
    link_to: Category.CategoryID
    name: CategoryID
  - dtype: float
    name: Price
  - dtype: category
    name: Title
  - dtype: float
    name: IsContext
  format: parquet
  name: AdsInfo
  source: AdsInfo.pqt
  time_column: null
tasks:
- columns:
  - dtype: primary_key
    name: AdID
  - dtype: datetime
    name: timestamp
  - dtype: float
    name: num_click
  evaluation_metric: mae
  format: parquet
  key_prediction_label_column: label
  key_prediction_query_idx_column: query_idx
  name: ad-ctr
  source: ad-ctr/{split}.pqt
  target_column: num_click
  target_table: AdsInfo
  task_emb: null
  task_type: regression
  time_column: timestamp
- columns:
  - dtype: primary_key
    name: UserID
  - dtype: datetime
    name: timestamp
  - dtype: category
    name: num_visits
  evaluation_metric: auroc
  format: parquet
  key_prediction_label_column: label
  key_prediction_query_idx_column: query_idx
  name: user-visits
  source: user-visits/{split}.pqt
  target_column: num_visits
  target_table: UserInfo
  task_emb: null
  task_type: classification
  time_column: timestamp
- columns:
  - dtype: primary_key
    name: UserID
  - dtype: datetime
    name: timestamp
  - dtype: category
    name: num_click
  evaluation_metric: auroc
  format: parquet
  key_prediction_label_column: label
  key_prediction_query_idx_column: query_idx
  name: user-clicks
  source: user-clicks/{split}.pqt
  target_column: num_click
  target_table: UserInfo
  task_emb: null
  task_type: classification
  time_column: timestamp