In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset_path = "../datasets/retailrocket"
griffin_dataset_path = "../griffin_datasets/retailrocket-pk"

In [4]:
all_views = pd.read_parquet(f"{dataset_path}/data/all_views.pqt")

In [5]:
pd.unique(all_views['added_to_cart'])

array([0, 1])

In [6]:
all_views

                      timestamp  visitorid  itemid  added_to_cart
0       2015-06-02 05:02:12.117     257597  355908              0
1       2015-06-02 05:50:14.164     992329  248676              0
2       2015-06-02 05:13:19.827     111016  318965              0
3       2015-06-02 05:12:35.914     483717  253185              0
4       2015-06-02 05:02:17.106     951259  367447              0
...                         ...        ...     ...            ...
2755956 2015-08-01 03:40:00.805     831605   57810              1
2756056 2015-08-01 03:02:36.086      10670  419736              1
2756074 2015-08-01 03:49:54.744     144106  141241              1
2756078 2015-08-01 03:30:07.937     804736  447661              1
2756090 2015-08-01 03:30:11.281     804736  346534              1

[2733644 rows x 4 columns]

In [7]:
# Add the id as a key to the data
all_views["viewid"] = all_views.index

In [8]:
all_views["added_to_cart"] = all_views["added_to_cart"].astype(bool)
all_views

                      timestamp  visitorid  itemid  added_to_cart   viewid
0       2015-06-02 05:02:12.117     257597  355908          False        0
1       2015-06-02 05:50:14.164     992329  248676          False        1
2       2015-06-02 05:13:19.827     111016  318965          False        2
3       2015-06-02 05:12:35.914     483717  253185          False        3
4       2015-06-02 05:02:17.106     951259  367447          False        4
...                         ...        ...     ...            ...      ...
2755956 2015-08-01 03:40:00.805     831605   57810           True  2755956
2756056 2015-08-01 03:02:36.086      10670  419736           True  2756056
2756074 2015-08-01 03:49:54.744     144106  141241           True  2756074
2756078 2015-08-01 03:30:07.937     804736  447661           True  2756078
2756090 2015-08-01 03:30:11.281     804736  346534           True  2756090

[2733644 rows x 5 columns]

In [9]:
train_data = pd.read_parquet(f"{dataset_path}/cvr/cvr-100k_train.pqt")
validation_data = pd.read_parquet(f"{dataset_path}/cvr/cvr-100k_validation.pqt")
test_data = pd.read_parquet(f"{dataset_path}/cvr/cvr-100k_test.pqt")

In [10]:
# find the row with viewid = 1364615
all_views[all_views["viewid"] == 1364615]

                      timestamp  visitorid  itemid  added_to_cart   viewid
1364615 2015-09-11 20:46:34.150     152963  440370          False  1364615

In [21]:
train_data

                      timestamp  visitorid  itemid  added_to_cart   viewid
1364615 2015-09-11 20:46:34.150     152963  440370          False  1364615
1364823 2015-09-11 20:46:38.985       7222  104526          False  1364823
1361646 2015-09-11 20:46:42.678     328104  263044          False  1361646
1352739 2015-09-11 20:46:44.133     198270  103497          False  1352739
1367274 2015-09-11 20:46:47.289     885529  453978          False  1367274
...                         ...        ...     ...            ...      ...
1426205 2015-09-16 05:00:59.059    1224201  437778          False  1426205
1426280 2015-09-16 05:01:01.797     728153  109116          False  1426280
1438545 2015-09-16 05:01:02.391    1027542  367102          False  1438545
1438550 2015-09-16 05:01:04.621     130543  340375          False  1438550
1426206 2015-09-16 05:01:12.012    1356121  172686          False  1426206

[80008 rows x 5 columns]

In [11]:
train_data["viewid"] = train_data.index
validation_data["viewid"] = validation_data.index
test_data["viewid"] = test_data.index

In [12]:
train_data["added_to_cart"] = train_data["added_to_cart"].astype(bool)
validation_data["added_to_cart"] = validation_data["added_to_cart"].astype(bool)
test_data["added_to_cart"] = test_data["added_to_cart"].astype(bool)

In [13]:
test_data["added_to_cart"].value_counts()

added_to_cart
False    9746
True      251
Name: count, dtype: int64

In [14]:
test_data.head()

                      timestamp  visitorid  itemid  added_to_cart   viewid
1447734 2015-09-17 03:08:36.195     457472  248636           True  1447734
1447750 2015-09-17 03:08:44.608    1024533  157970          False  1447750
1447759 2015-09-17 03:08:45.577     801519  303960          False  1447759
1450203 2015-09-17 03:08:52.844    1142130  236477          False  1450203
1450200 2015-09-17 03:08:56.353    1227528  389856          False  1450200

In [18]:
item_availability = pd.read_parquet(f"{dataset_path}/data/item_availability.pqt")
item_availability["item_availability_id"] = np.arange(len(item_availability))
item_availability

                  timestamp  itemid available  item_availability_id
5       2015-07-05 03:00:00  285026         0                     0
15      2015-07-19 03:00:00  186518         0                     1
79      2015-06-07 03:00:00  423682         0                     2
82      2015-06-14 03:00:00  316253         1                     3
96      2015-07-19 03:00:00  430459         0                     4
...                     ...     ...       ...                   ...
9275846 2015-08-30 03:00:00  229797         0               1503634
9275856 2015-08-02 03:00:00  225378         1               1503635
9275890 2015-05-31 03:00:00  356167         0               1503636
9275892 2015-08-09 03:00:00  200211         0               1503637
9275897 2015-07-05 03:00:00   74745         0               1503638

[1503639 rows x 4 columns]

In [19]:
item_categories = pd.read_parquet(f"{dataset_path}/data/item_categories.pqt")
item_categories["item_categories_id"] = np.arange(len(item_categories))
item_categories

                  timestamp  itemid  category  item_categories_id
0       2015-06-28 03:00:00  460429      1338                   0
140     2015-05-24 03:00:00  281245      1277                   1
151     2015-06-28 03:00:00   35575      1059                   2
189     2015-07-19 03:00:00    8313      1147                   3
197     2015-07-26 03:00:00   55102        47                   4
...                     ...     ...       ...                 ...
9275798 2015-06-07 03:00:00  255696      1404              788209
9275823 2015-05-10 03:00:00  390760       324              788210
9275831 2015-07-26 03:00:00  211844       256              788211
9275873 2015-06-28 03:00:00  444741       511              788212
9275879 2015-06-28 03:00:00   97513      1385              788213

[788214 rows x 4 columns]

In [20]:
item_property = pd.read_parquet(f"{dataset_path}/data/item_properties.pqt")
item_property["item_property_id"] = np.arange(len(item_property))
item_property

,timestamp,itemid,property,value,item_property_id
1,2015-09-06 03:00:00,206783,888,1116713 960601 n277.200,0
2,2015-08-09 03:00:00,395014,400,n552.000 639502 n720.000 424566,1
3,2015-05-10 03:00:00,59481,790,n15360.000,2
4,2015-05-17 03:00:00,156781,917,828513,3
6,2015-06-14 03:00:00,89534,213,1121373,4
...,...,...,...,...,...
9275898,2015-06-07 03:00:00,236931,929,n12.000,17984044
9275899,2015-08-30 03:00:00,455746,6,150169 639134,17984045
9275900,2015-08-16 03:00:00,347565,686,610834,17984046
9275901,2015-06-07 03:00:00,287231,867,769062,17984047
9275902,2015-09-13 03:00:00,275768,888,888666 n10800.000 746840 1318567,17984048

In [21]:
# Save the parquet files under griffin_dataset
import shutil
import os
shutil.rmtree(griffin_dataset_path, ignore_errors=True)
shutil.copytree(dataset_path, griffin_dataset_path)

'../griffin_datasets/retailrocket-pk'

In [22]:
# remove the cvr folder
shutil.rmtree(f"{griffin_dataset_path}/cvr", ignore_errors=True)
os.makedirs(f"{griffin_dataset_path}/cvr", exist_ok=True)
# Save the parquet files
train_data.to_parquet(f"{griffin_dataset_path}/cvr/cvr-100k_train.pqt")
validation_data.to_parquet(f"{griffin_dataset_path}/cvr/cvr-100k_validation.pqt")
test_data.to_parquet(f"{griffin_dataset_path}/cvr/cvr-100k_test.pqt")
all_views.to_parquet(f"{griffin_dataset_path}/data/all_views.pqt")

item_availability.to_parquet(f"{griffin_dataset_path}/data/item_availability.pqt")
item_categories.to_parquet(f"{griffin_dataset_path}/data/item_categories.pqt")
item_property.to_parquet(f"{griffin_dataset_path}/data/item_properties.pqt")

In [ ]:
# Manually update the config file

dataset_name: retailrocket
tables:
  - name: View
    source: data/all_views.pqt
    format: parquet
    columns:
      - name: viewid
        dtype: primary_key
      - name: itemid
        dtype: foreign_key
        link_to: Item.itemid
      - name: visitorid
        dtype: foreign_key
        link_to: Visitor.id
      - name: added_to_cart
        dtype: category
      - name: timestamp
        dtype: datetime
    time_column: timestamp
  - name: Category
    source: data/category_tree.pqt
    format: parquet
    columns:
      - name: categoryid
        dtype: primary_key
      - name: parentid
        dtype: foreign_key
        link_to: Category.categoryid
  - name: ItemAvailability
    source: data/item_availability.pqt
    format: parquet
    columns:
      - name: item_availability_id
        dtype: primary_key
      - name: itemid
        dtype: foreign_key
        link_to: Item.itemid
      - name: available
        dtype: category
      - name: timestamp
        dtype: datetime
    time_column: timestamp
  - name: ItemCategory
    source: data/item_categories.pqt
    format: parquet
    columns:
      - name: item_categories_id
        dtype: primary_key
      - name: itemid
        dtype: foreign_key
        link_to: Item.itemid
      - name: category
        dtype: foreign_key
        link_to: Category.categoryid
      - name: timestamp
        dtype: datetime
    time_column: timestamp
  - name: ItemProperty
    source: data/item_properties.pqt
    format: parquet
    columns:
      - name: item_property_id
        dtype: primary_key
      - name: itemid
        dtype: foreign_key
        link_to: Item.itemid
      - name: property
        dtype: category
      - name: value
        dtype: text
      - name: timestamp
        dtype: datetime
    time_column: timestamp
tasks:
  - name: cvr
    source: cvr/cvr-100k_{split}.pqt
    format: parquet
    columns:
      - name: viewid
        dtype: primary_key
      - name: itemid
        dtype: foreign_key
        link_to: Item.itemid
      - name: visitorid
        dtype: foreign_key
        link_to: Visitor.id
      - name: added_to_cart
        dtype: category
      - name: timestamp
        dtype: datetime
    time_column: timestamp
    evaluation_metric: auroc
    target_column: added_to_cart
    target_table: View
    task_type: classification